services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lynkr
      POSTGRES_PASSWORD: lynkr
      POSTGRES_DB: lynkr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
